# Generated by Django 2.2.16 on 2022-03-22 18:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shoppingcart',
            old_name='shopping_cart',
            new_name='recipe',
        ),
    ]
