# Generated by Django 2.2.16 on 2022-03-31 18:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='follow',
            options={'ordering': ['-id'], 'verbose_name': 'Подписки', 'verbose_name_plural': 'Подписки'},
        ),
    ]
